services:
 prometheus:
   image: prom/prometheus:v2.53.1
   container_name: prometheus
   ports:
     # port number on the left hand side can be changed to other value if 9090 is in use
     - 9090:9090
   command:
     - '--config.file=/etc/prometheus/prometheus.yaml'
   volumes:
     - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
     - prometheus-data:/prometheus
   healthcheck:
     test: [ "CMD", "wget", "--spider", "http://localhost:9090" ]
     interval: 10s
     timeout: 15s
     retries: 10
     start_period: 40s
   restart: unless-stopped
 grafana:
   image: grafana/grafana-oss:11.1.3
   container_name: grafana
   depends_on:
     - prometheus
   ports:
     # port number on the left hand side can be changed to other value if 3000 is in use
     - 3000:3000
   volumes:
     - grafana-data:/var/lib/grafana
     # provisioning configs
     - ./config/grafana/provisioning:/etc/grafana/provisioning
     # dashboards to provision
     - ./config/grafana/dashboards:/etc/grafana/artifacts/dashboards
   healthcheck:
     test: [ "CMD", "wget", "--spider", "http://localhost:3000" ]
     interval: 10s
     timeout: 15s
     retries: 10
     start_period: 40s
   restart: unless-stopped
   
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
