services:
 prometheus:
   image: prom/prometheus:v2.53.1
   container_name: prometheus
   ports:
     # port number on the left hand side can be changed to other value if 9090 is beeing in use
     - 9091:9090
   command:
     - '--config.file=/etc/prometheus/prometheus.yaml'
   volumes:
     - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
     - prometheus-data:/prometheus
   restart: unless-stopped
 grafana:
   image: grafana/grafana-oss:11.1.3
   container_name: grafana
   ports:
     # port number on the left hand side can be changed to other value if 3000 is beeing in use
     - 3002:3000
   volumes:
     - grafana-data:/var/lib/grafana
     # provisioning configs
     - ./config/grafana/provisioning:/etc/grafana/provisioning
     # dashboards to privision
     - ./config/grafana/dashboards:/etc/grafana/artifacts/dashboards
   restart: unless-stopped
   
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
